spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/user_org_system?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    gateway:
      routes:
        - id: orgSystem
          uri: lb://org
          predicates:
            - Path=/org/**
          filters:
            - StripPrefix=1

        - id: roleSystem
          uri: lb://role
          predicates:
            - Path=/role/**
          filters:
            - StripPrefix=1

        - id: userSystem
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379
server:
  port: 8091
user:
  container:
    use-redis: false
eureka:
  host: 127.0.0.1
  port: 8090
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/*
  configuration:
    map-underscore-to-camel-case: true